root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -tags dev -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"

  delay = 20
  exclude_dir = ["assets", "tmp"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true


[log]
  time = true

[env]
  APP_ENV = "dev"

[misc]
  clean_on_exit = true
